# Generated by Django 5.0.1 on 2026-06-24 21:48

import api.models
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.new_id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("startDate", models.DateField(blank=True, null=True)),
                ("endDate", models.DateField(blank=True, null=True)),
                ("budget", models.CharField(blank=True, default="", max_length=255)),
                (
                    "completionStatus",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "objectives",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "assumptions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "scopesIncluded",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "scopesExcluded",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "risks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "sponsors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "completionRequirements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "qualityAssurance",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "KPIs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "informationLinks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "userIDs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=24),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "projectManagerIDs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=24),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "contributorIDs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=24),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "otherProjectDependencies",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=24),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "teams",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=24),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.new_id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("firstName", models.CharField(blank=True, default="", max_length=255)),
                ("lastName", models.CharField(blank=True, default="", max_length=255)),
                (
                    "teamIDs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=24),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("apiKey", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.new_id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=8)),
                ("order", models.IntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskStatuses",
                        to="api.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.new_id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("startDate", models.DateField(blank=True, null=True)),
                ("endDate", models.DateField(blank=True, null=True)),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("durationMinutes", models.IntegerField(default=0)),
                (
                    "objectives",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "scopesIncluded",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "scopesExcluded",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "contributorIDs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=24),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "otherProjectDependencies",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=24),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "otherTaskDependencies",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=24),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "parentTaskID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="api.task",
                    ),
                ),
                (
                    "projectID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="api.project",
                    ),
                ),
                (
                    "statusId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="api.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.new_id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dateCreated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("mood", models.IntegerField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "projectID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="api.project",
                    ),
                ),
                (
                    "taskID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="api.task",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
